spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab_management
    username: postgres
    password: sipirili
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 8080
#jwt.secret: "StrawberryFieldsForever"