POST http://localhost:8080/autenticar
Content-Type: application/json

{
  "username": "carlos.montoya@profesor.buap.mx",
  "password": "admin"
}

> {% client.global.set("auth_token", response.body.token); %}

###

GET localhost:8080/api/usuarios
Authorization: Bearer {{auth_token}}


###

GET localhost:8080/api/colaboradores/
Authorization: Bearer {{auth_token}}


###

GET localhost:8080/api/colaboradores/2
Authorization: Bearer {{auth_token}}


###

GET http://localhost:8080/api/documentos
Authorization: Bearer {{auth_token}}
