POST http://localhost:8080/autenticar
Content-Type: application/json

{
  "username": "carlos.montoya@profesor.buap.mx",
  "password": "admin"
}

> {% client.global.set("auth_token", response.body.token); %}

###

GET localhost:8080/api/usuarios
Authorization: Bearer {{auth_token}}


###

GET localhost:8080/api/colaboradores/
Authorization: Bearer {{auth_token}}


###

GET localhost:8080/api/colaboradores/2
Authorization: Bearer {{auth_token}}


###

GET localhost:8080/api/documentos
Authorization: Bearer {{auth_token}}


### Profesores

GET localhost:8080/api/profesores
Authorization: Bearer {{auth_token}}

###

POST http://localhost:8080/api/profesores
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "correo": "luis.perez@profesor.buap.mx",
  "password": "luis.perez",
  "responsable": true,
  "nombre": "Luis",
  "apellidoPaterno": "Perez",
  "apellidoMaterno": "Gomez",
  "matricula": "201135410",
  "telefono": "21244495121",
  "activo": true
}
